name: ReleaseCenter Deployment Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Upload to S3 (dev)
        uses: ./.github/actions/s3-upload
        with:
          s3-folder-name: dev

  deploy-to-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run python file
        run: python hello.py
      - name: Upload to S3 (test)
        uses: ./.github/actions/s3-upload
        with:
          s3-folder-name: test

  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment: production-env
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Upload to S3 (prod)
        uses: ./.github/actions/s3-upload
        with:
          s3-folder-name: prod
        
